image: Ubuntu2204  # образ для сборки

stack: node 20  # окружение

branches:
  only:
    - master  # ветка git
    - main

cache: node_modules  # кеширование

install:
  - yarn  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - yarn build   # команда сборки

test_script:
  - yarn lint && yarn test  # скрипт тестирования

deploy_script:  # скрипт развёртывания
  - git config --global credential.helper store
  - git config --global user.name AppVeyor
  - git config --global user.email ci@appveyor.com
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - npx gh-pages -d dist -u "appveyor-bot <ci@appveyor>"

version: 1.0.{build}
environment:
  token:
    secure: UuGocukbD9dM5BWalqQg6ALRHbV6uFigodBxd3GBdpvEJqL1Wv8SpCe67xXxPYxR
  git: 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
